[package]
name = "actix_app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
num_cpus = "1.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"